on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    environment:
      name: ${{ github.ref_name }}
    env:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    runs-on: ubuntu-latest
    outputs:
        latest_tag: ${{ steps.set_latest_tag.outputs.latest_tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Install musl cc
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools musl-dev musl
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache: false
      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          release_branches: main
          tag_prefix: v
      - name: Go Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/kaytu-io.insteadOf https://github.com/kaytu-io
      - name: Build plugin app
        working-directory: ./steampipe-plugin-aws
        run: make build
      - name: Pack plugin build
        working-directory: ./steampipe-plugin-aws
        run: |
          tar -cvf build.tar build
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          name: steampipe-plugin-aws
          path: ./steampipe-plugin-aws/build.tar
          retention-days: 1
      - name: Build lambda describer app
        working-directory: .
        run: make build
      - name: Pack lambda describer build
        working-directory: .
        run: |
          tar -cvf build.tar build
      - name: Upload lambda describer artifact
        uses: actions/upload-artifact@v3
        with:
          name: kaytu-aws-describer
          path: ./build.tar
          retention-days: 1
      - name: Set latest tag output
        id: set_latest_tag
        run: |
          if [[ -z "${{ steps.tag_version.outputs.new_tag }}" ]]; then
            echo "latest_tag=${{ steps.tag_version.outputs.new_tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "latest_tag=${{ steps.tag_version.outputs.previous_tag }}" >> "$GITHUB_OUTPUT"
          fi
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download plugin artifact
        uses: actions/download-artifact@v3
        with:
          name: steampipe-plugin-aws
          path: .
      - name: Unpack plugin artifact
        run: |
          tar -xvf build.tar
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
      - name: Build and push Docker images for plugin
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/steampipe-plugin-aws:0.0.1
            ${{ vars.DOCKER_REGISTRY }}/steampipe-plugin-aws:${{ needs.build.outputs.latest_tag }}
          file: steampipe-plugin-aws/docker/Dockerfile
          context: .
      - name: Download lambda describer artifact
        uses: actions/download-artifact@v3
        with:
          name: kaytu-aws-describer
          path: .
      - name: Unpack lambda describer artifact
        run: |
          tar -xvf build.tar
      - name: Build and push Docker images for lambda describer
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          tags: |
            ${{ vars.DOCKER_REGISTRY }}/kaytu-aws-describer:latest
            ${{ vars.DOCKER_REGISTRY }}/kaytu-aws-describer:${{ needs.build.outputs.latest_tag }}
          file: Dockerfile
          context: .
